#!/bin/bash

################################################################################
## theming app for instantOS                                                  ##
## Aims to configure as much applications as possible to conform to the theme ##
################################################################################

cd
source /usr/share/paperbash/import.sh

pb git
pb config
pb gtk
pb instantos

if [ -n "$2" ]; then
    APPLYTHEME=$2
else
    if [ -e ~/instantos/themes/config ]; then
        APPLYTHEME=$(cat ~/instantos/themes/config)
    else
        echo "using default theme"
        APPLYTHEME="arc"
    fi
fi

source /usr/share/instantthemes/$APPLYTHEME.sh
ACTION=${1:-apply}

tapply() {
    echo "applying $APPLYTHEME theme"
    instanttheme "$APPLYTHEME"
    themeapply
    # some things result in empty lines in xresources
    sed -i 's/\\n//g' ~/.Xresources
    instantdpi
}

installfont() {
    convert -list font | grep -iq "$1" && return
    mkdir -p ~/.local/share/fonts &>/dev/null
    mkdir -p /tmp/instantosfonts/"$1" || exit 1
    pushd .
    cd /tmp/instantosfonts/"$1" || exit

    case "$2" in
        google)
            wget -qO font.zip "https://fonts.google.com/download?family=$3"
            unzip font.zip
            rm LICENSE.txt
            rm font.zip
            ;;
        script)
            if [ -e /usr/share/instantthemes/scripts/"$3".sh ]
            then
                /usr/share/instantthemes/scripts/"$3".sh
            fi
            ;;
    esac

    mv ./* ~/.local/share/fonts
    popd

    rm -rf /tmp/instantosfonts

}

# installs a theme from git
# installtheme themename themerepo
# theme needs to be installable as a normal user with an install.sh script

installtheme() {
    if themeexists "$1" &>/dev/null; then
        return
    fi

    mkdir -p /tmp/instantostemptheme
    pushd .
    cd /tmp/instantostemptheme || exit 1
    if grep -q '://' <<< "$2"
    then
        git clone --depth=1 "$2" temptheme
    else
        git clone --depth=1 "https://github.com/$2" temptheme
    fi

    cd temptheme || exit
    ./install.sh
    rm -rf /tmp/instantostemptheme
    popd || exit 1
}

readtheme() {
    source /usr/share/instantthemes/config/"$1"
    PAPIRUSICONS="Papirus,PapirusDevelopmentTeam/papirus-icon-theme"

    GTKTHEME="${GTKTHEME:-Arc}"
    DGTKTHEME="${DGTKTHEME:-$GTKTHEME}"
    GTKICONS="${GTKICONS:-$PAPIRUSICONS}"
    DGTKICONS="${DGTKICONS:-$DGTKICONS}"
    
    ROFITHEME="${ROFITHEME:-$THEMENAME}"
    CURSORTHEME=${CURSORTHEME:-elementary-instantos}
    XTHEME="${XTHEME:-$THEMENAME}"
    DUNSTTHEME="${DUNSTTHEME:-$THEMENAME}"


    if grep -q ',' <<< "$GTKTHEME"
    then
        installtheme "$(echo "$GTKTHEME" | grep -o '^[^,]*')" "$(echo "$GTKTHEME" | grep -o '[^,]*$')"
    fi

    if grep -q ',' <<< "$GTKICONS"
    then
        installtheme "$(echo "$GTKICONS" | grep -o '^[^,]*')" "$(echo "$GTKICONS" | grep -o '[^,]*$')"
    fi
    
}

case "$ACTION" in
a)
    tapply
    ;;
f)
    themefetch
    ;;
d)
    if command -v darktheme; then
        darktheme
        exit
    else
        echo "no dark theme available for $APPLYTHEME"
    fi
    ;;
l)
    if command -v lighttheme; then
        lighttheme
        exit
    else
        echo "no light theme available for $APPLYTHEME"
    fi
    ;;
*)
    themefetch
    tapply
    ;;
esac
