#!/bin/bash

################################################################################
## theming app for instantOS                                                  ##
## Aims to configure as much applications as possible to conform to the theme ##
################################################################################

source /usr/share/instantthemes/utils/functions.sh || exit 1

if ! iconf theme; then
    iconf theme arc
fi

APPLYTHEME="$(iconf theme:arc)"

ACTION="${1:-apply}"

# installs font for user
# pulls from google font or fetch scripts

# installs a theme or icon set from git
# installgtktheme themename themerepo
# theme needs to be installable as a normal user with an install.sh script

# check if theme is installed
installtheme() {

    echo "installing theme $(tparse name)"

    if tparse q gtk; then
        installfont gtk
        if tparse gtk.theme.name && ! themeexists "$(gtk.theme.name)"; then
            installgtktheme gtk.theme
        fi

        if tparse gtk.icons.name && ! themeexists "$(gtk.icons.name)"; then
            installgtktheme gtk.icons
        fi
    fi

    if tparse q terminal; then
        installfont terminal
    fi

    # fetch cursor if not preinstalled and not existing
    if ! grep -q 'elementary' <<<"$CURSORTHEME"; then
        if ! [ -e ~/.icons/"$CURSORTHEME" ]; then
            papercursor "$CURSORTHEME"
        fi
    fi

    setcursor "$CURSORTHEME"
    rofitheme "$ROFITHEME"
    dunsttheme "$DUNSTTHEME"
    xtheme "$XTHEME"
    gtkfont "$GTKFONTNAME"
    # gtk theme and gtk icons are done seperately
}

lighttheme() {
    gtkicons "$(tparse gtk.icons.name)"
    gtktheme "$(tparse gtk.theme.name)"
}

darktheme() {
    tparse q gtk.dark || return
    setgtkicons "$(tparse gtk.dark.icons)"
    setgtktheme "$(tparse gtk.dark.theme)"
}

tapply() {
    echo "applying $APPLYTHEME theme"
    readtheme "$APPLYTHEME"
    # some things result in empty lines in xresources
    sed -i 's/\\n//g' ~/.Xresources
    instantdpi
}

case "$ACTION" in
a*)
    installtheme "$APPLYTHEME"
    ;;
d*)
    themenames
    darktheme
    ;;
l*)
    themenames
    lighttheme
    ;;

esac
